import { Response } from 'express';
import { AuthRequest } from '../middleware/auth.middleware';
import { AIService } from '../services/ai.service';
import { db } from '../lib/firebase';
import { ImageService } from '../services/image.service';
import PptxGenJS from 'pptxgenjs';
import * as path from 'path';
import * as fs from 'fs';
import axios from 'axios';

// Helper to fetch image and convert to base64 with better error handling and timeout
const fetchImageBase64 = async (url: string): Promise<string | null> => {
    try {
        console.log(`[PPT] Fetching image from: ${url}`);
        const response = await axios.get(url, {
            responseType: 'arraybuffer',
            timeout: 15000, // 15 seconds timeout for AI generation
            headers: {
                'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
            }
        });
        const base64 = Buffer.from(response.data, 'binary').toString('base64');
        const contentType = response.headers['content-type'];
        return `data:${contentType};base64,${base64}`;
    } catch (error: any) {
        console.error("[PPT] Image fetch failed:", url, error.message);
        return null;
    }
};

export const generatePPTFile = async (req: AuthRequest, res: Response) => {
    try {
        const { topic, slides } = req.body;
        if (!topic) {
            return res.status(400).json({ error: "Topic is required" });
        }

        let slideData = slides;

        if (!slideData) {
            console.log(`[PPT] Generating new presentation for topic: ${topic}`);
            const aiResponse = await AIService.generatePPTSlides(topic);
            slideData = aiResponse.slides;

            if (!slideData || !Array.isArray(slideData)) {
                throw new Error("AI failed to return valid slide content");
            }

            // Save to History (Firestore)
            const teacherId = req.user?.id;
            if (teacherId) {
                await db.collection('lessonPlans').add({
                    title: `${topic} Presentation`,
                    content: { slides: slideData },
                    type: 'PRESENTATION',
                    teacherId,
                    status: 'PUBLISHED',
                    createdAt: new Date().toISOString(),
                    updatedAt: new Date().toISOString()
                });
            }
        }

        const pptx = new PptxGenJS();
        pptx.layout = 'LAYOUT_16x9';

        // Styling Config
        const BG_COLOR = 'F8FAFC';
        const TITLE_COLOR = '1E293B';
        const ACCENT_COLOR = '2563EB';
        const TEXT_COLOR = '475569';

        // Loop through slides
        for (let i = 0; i < slideData.length; i++) {
            const slideItem = slideData[i];
            const slide = pptx.addSlide();
            slide.background = { fill: BG_COLOR };

            if (i === 0) {
                // Title Slide
                try {
                    const titleImageUrl = await ImageService.getRandomImage(`${topic} background`);
                    const titleImageBase64 = await fetchImageBase64(titleImageUrl);
                    if (titleImageBase64) {
                        slide.addImage({
                            data: titleImageBase64,
                            x: 0, y: 0, w: '100%', h: '100%'
                        });
                    }
                } catch (e) { }

                slide.addText(slideItem.title, {
                    x: 0,
                    y: '40%',
                    w: '100%',
                    h: 1,
                    fontSize: 48,
                    bold: true,
                    color: TITLE_COLOR,
                    align: 'center',
                    fontFace: 'Arial'
                });

                slide.addText("Generated by AI CoTeacher", {
                    x: 0,
                    y: '55%',
                    w: '100%',
                    h: 0.5,
                    fontSize: 18,
                    color: ACCENT_COLOR,
                    align: 'center',
                    italic: true
                });

                // Decorative Line
                slide.addShape(pptx.ShapeType.rect, {
                    x: '40%', y: '52%', w: '20%', h: 0.05,
                    fill: { color: ACCENT_COLOR }
                });

            } else {
                // Content Slide
                slide.addText(slideItem.title, {
                    x: 0.5,
                    y: 0.5,
                    w: 9,
                    h: 0.8,
                    fontSize: 32,
                    bold: true,
                    color: TITLE_COLOR,
                    fontFace: 'Arial'
                });

                // Bullets
                const points = Array.isArray(slideItem.points) ? slideItem.points : [];
                slide.addText(
                    points.map((p: string) => ({
                        text: p,
                        options: { bullet: true, color: TEXT_COLOR, margin: [0, 0, 0, 10] }
                    })),
                    {
                        x: 0.5,
                        y: 1.5,
                        w: 5,
                        h: 3.5,
                        fontSize: 18,
                        color: TEXT_COLOR,
                        valign: 'top'
                    }
                );

                // Relevant Image
                try {
                    const query = slideItem.imageQuery || slideItem.title || topic;
                    const imageUrl = await ImageService.getRandomImage(query);
                    const imageBase64 = await fetchImageBase64(imageUrl);

                    if (imageBase64) {
                        slide.addImage({
                            data: imageBase64,
                            x: 6,
                            y: 1,
                            w: 3.5,
                            h: 3.5,
                            sizing: { type: 'cover', w: 3.5, h: 3.5 }
                        });

                        // Image border/frame
                        slide.addShape(pptx.ShapeType.rect, {
                            x: 5.9, y: 0.9, w: 3.7, h: 3.7,
                            line: { color: ACCENT_COLOR, width: 2 }
                        });
                    }
                } catch (err) {
                    console.error("Image skip for slide", i, err);
                }
            }

            // Footer
            slide.addText(`Slide ${i + 1} | AI CoTeacher | Topic: ${topic}`, {
                x: 0.5, y: 5.3, w: 9, h: 0.3,
                fontSize: 10, color: '94A3B8', align: 'right'
            });
        }

        const fileName = `presentation_${Date.now()}.pptx`;
        const uploadsDir = path.join(process.cwd(), 'uploads');
        const tempPath = path.join(uploadsDir, fileName);

        if (!fs.existsSync(uploadsDir)) {
            fs.mkdirSync(uploadsDir, { recursive: true });
        }

        await pptx.writeFile({ fileName: tempPath });

        res.download(tempPath, `${topic.replace(/\s+/g, '_')}_Presentation.pptx`, (err) => {
            if (fs.existsSync(tempPath)) fs.unlinkSync(tempPath);
        });

    } catch (error: any) {
        console.error("PPT Generation Error:", error);
        res.status(500).json({ error: "Failed to generate PowerPoint", details: error.message });
    }
};
